masters/urls.py
from django.urls import path
from .views import*



app_name = 'masters'

urlpatterns = [
    path('dashboard/', baseview.as_view(), name='dashboard'),
    path('productcategory/', productcategoryview.as_view(), name='productcategory'),
    # Delete a product category
    path('productcategory/delete/<int:pk>/', delete_package_type, name='delete_productcategory'),
    # Export product categories (excel or pdf)
    path('productcategory/export/<str:export_type>/', export_package_types, name='export_productcategory'),
    path('tankmaster/', tankmasterview.as_view(), name='tankmaster'),

    # Delete
    path('tankmaster/delete/<int:pk>/', delete_tank, name='delete_tank'),

    # Export
    path('tankmaster/export/<str:export_type>/', export_tanks, name='export_tanks'),
        path('fuel-rate/', FuelRateView.as_view(), name='fuel_rate'),
        path('fuel-rate/export/<str:export_type>/', export_fuel_rates, name='export_fuel_rates'),
        path('fuel-rate/delete/<int:pk>/', delete_fuel_rate, name='delete_fuel_rate'),

    # PAGE LOAD (GET)
    path(
        "nozzle-staff-alloc/",
        NozzleStaffAllocPageView.as_view(),
        name="nozzle_staff_alloc"
    ),

    # SAVE (POST)
    path(
        "nozzle-staff-alloc/save/",
        NozzleStaffAllocSaveView.as_view(),
        name="nozzle_staff_alloc_save"
    ),

        path('nozzle-staff-alloc/delete/', nozzle_staff_alloc_delete, name='nozzle_staff_alloc_delete'),
    path('entry/create/', EntryMasterView.as_view(), name='entry_master'),
    path('entry/delete/<int:pk>/', EntryDeleteView.as_view(), name='entry_delete'),
    path('product-delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'), 
    path('entries/export/<str:export_type>/',export_companies, name='export_companies'),
    path(
        'tank/delete/<int:pk>/',
        ProductStockDeleteView.as_view(),
        name='tank_delete'
    ),
        path(
        'export/products/<str:export_type>/',
        export_products,
        name='export_products'
    ),

       path(
        'fuel-nozzle/',
        FuelNozzleMasterView.as_view(),
        name='fuel_nozzle_master'
    ),

     path('delete-fuel-entry/<int:pk>/', FuelEntryDeleteView.as_view(), name='delete_fuel_entry'),


    path(
    'delete-fuel-nozzle/<int:pk>/',
    FuelNozzleDeleteView.as_view(),
    name='delete_fuel_nozzle'
    ),


    # urls.py
path(
    'tank-details/<int:tank_id>/',
    get_tank_details,
    name='get_tank_details'
),

    path(
        'fuel-entry-report/<str:export_type>/',
        export_fuel_entries,
        name='fuel_entry_report'
    ),


        path(
        'nozzle-fuel-report/<str:export_type>/',
        export_nozzle_fuel_entries,
        name='nozzle_fuel_report'
    ),









        # Vehicle Type Master
    path(
        'vehicle-type/',
        VehicleTypeMasterView.as_view(),
        name='vehicle_type_master'
    ),

    # Delete Vehicle Type
    path(
        'vehicle-type/delete/<int:pk>/',
        delete_vehicle_type,
        name='delete_vehicle_type'
    ),

    # Export Vehicle Type (excel / pdf)
    path(
        'vehicle-type/export/<str:export_type>/',
        export_vehicle_type_master,
        name='export_vehicle_type_master'
    ),
    path('managecustomerview/', managecustomerview.as_view(), name='managecustomerview'),
    path('indentissueview', indentissueview.as_view(), name='indentissueview'),
    path('customeroutstandingview/', customeroutstandingview.as_view(), name='customeroutstandingview'),
    path('supplier/', SupplierView.as_view(), name='supplier'),
    path(
    'supplier/delete/<int:pk>/',
    delete_supplier,
    name='delete_supplier'
    ),
    path('supplieroutstandingview/', supplieroutstandingview.as_view(), name='supplieroutstandingview'),
    path(
        'staff/',
        StaffMasterView.as_view(),
        name='staffmaster'
    ),
    path(
    'supplier/export/<str:export_type>/',
    export_supplier_master,
    name='export_supplier_master'
),
    path('staff/delete/<int:pk>/', delete_staff, name='delete_staff'),

    path('staffs/export/<str:export_type>/',export_staff_list, name='export_staff'),


    # calibration chart urls
    # List + Create + Update
    path(
        'calibration-chart/',
        CalibrationChartView.as_view(),
        name='calibrationchart'
    ),

    # Delete
    path(
        'calibration-chart/delete/<int:pk>/',
        delete_calibration_chart,
        name='delete_calibrationchart'
    ),

    # Export (Excel)
path(
    'calibration-chart/export/<str:export_type>/',
    export_calibration_chart,
    name='export_calibration_chart'
),

    # urls.py
path(
    "ajax/get-dip-by-tank/",
    get_dip_by_tank_volume,
    name="get_dip_by_tank_volume"
),

path(
    'calibration-chart/<int:chart_id>/export/<str:export_type>/',
    export_dip_entries,
    name='export_dip_entries'
),




    path('densitychartview/', densitychartview.as_view(), name='densitychartview'),
    path('resetshiftview/', resetshiftview.as_view(), name='resetshiftview'),
    path('deleteshiftview/', deleteshiftview.as_view(), name='deleteshiftview'),
     path('groupmaster/', GroupMasterView.as_view(), name='groupmaster'),

    # Delete Group
    path('groupmaster/delete/<int:pk>/', delete_group_master, name='delete_groupmaster'),

    # Export Group Master
    path('groupmaster/export/<str:export_type>/', export_group_master, name='export_groupmaster'),
    path('ledgermaster/', LedgerMasterView.as_view(), name='ledgermaster'),

    # Delete ledger
    path('ledger/delete/<int:pk>/',delete_ledger_master,name='delete_ledger_master'),

    # Export ledger (excel/pdf)
    path('ledgermaster/export/<str:export_type>/', export_ledger_master, name='export_ledgermaster'),
    path('bankdetailsview/', bankdetailsview.as_view(), name='bankdetailsview'),
        # ================= MODE OF PAY =================
    path(
        'mode-of-pay/',
        ModeOfPayView.as_view(),
        name='modeofpay'
    ),

    path(
        'mode-of-pay/delete/<int:pk>/',
        delete_mode_of_pay,
        name='delete_modeofpay'
    ),

    path(
        'mode-of-pay/export/<str:export_type>/',
        export_mode_of_pay,
        name='export_modeofpay'
    ),
        # Tax Master list, add, edit
    path('tax-master/', TaxMasterView.as_view(), name='taxmaster'),

    # Delete Tax Master
    path('tax-master/delete/<int:pk>/', delete_tax_master, name='delete_taxmaster'),

    # Export Tax Master (excel/pdf)
    path('tax-master/export/<str:export_type>/', export_tax_master, name='export_taxmaster'),
    path('stockadjustmentview/', stockadjustmentview.as_view(), name='stockadjustmentview'),

]

petromate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
from petromate import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('website.urls')),
    path('captcha/', include('captcha.urls')),
    path('account/', include('accounts.urls')),
    path('masters/', include('masters.urls')),
    path('transactions/', include('transactions.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

masters/views.py
from itertools import product
from multiprocessing import context
from aiohttp import request
from django.shortcuts import render
from django.views.generic import TemplateView, View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import*
from .forms import*
from django.core.paginator import Paginator
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse
import csv
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from django.db import transaction

# Create your views here.

class baseview(TemplateView):
    template_name = "masters/dashboard.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    

class productcategoryview(TemplateView):

    template_name = "masters/productcategory.html"

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        all_category_type = productcategory.objects.all().order_by('-id')

        paginator = Paginator(all_category_type, 10)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        packagetype_id = self.request.GET.get('edit')
        form = None
        editing_packagetype = None

        if packagetype_id:
            try:
                editing_packagetype = productcategory.objects.get(id=packagetype_id)
                form = ProductCategoryForm(instance=editing_packagetype)
                context['editing_packagetype'] = editing_packagetype
            except productcategory.DoesNotExist:
                messages.error(self.request, 'Category/Type not found!')

        if not form:
            form = ProductCategoryForm()

        context.update({
            'form': form,
            'packages': page_obj,
            'queryset': page_obj,
            'total_packagetype': all_category_type.count(),
        })

        return context

    def post(self, request, *args, **kwargs):
        packagetype_id = request.POST.get('packagetype_id')

        if packagetype_id:
            package_instance = get_object_or_404(productcategory, id=packagetype_id)
            form = ProductCategoryForm(request.POST, instance=package_instance)
        else:
            package_instance = None
            form = ProductCategoryForm(request.POST)

        if form.is_valid():
            category_type = form.cleaned_data.get('category_type')
            description = form.cleaned_data.get('description')

            # ✅ DUPLICATE CHECK
            if category_type and description:
                duplicate_qs = productcategory.objects.filter(
                    category_type=category_type,
                    description__iexact=description  # case-insensitive check
                )
                if packagetype_id:
                    duplicate_qs = duplicate_qs.exclude(id=packagetype_id)

                if duplicate_qs.exists():
                    context = self.get_context_data()
                    context['form'] = form
                    context['editing_packagetype'] = package_instance if packagetype_id else None
                    context['duplicate_error'] = "This Category/Type with the same description already exists."
                    return self.render_to_response(context)

            # Save the instance
            package_instance = form.save(commit=False)

            if 'is_active' not in request.POST:
                package_instance.is_active = False

            if packagetype_id:
                package_instance.updated_by = request.user
                action = "updated"
            else:
                package_instance.created_by = request.user
                package_instance.updated_by = request.user
                action = "created"

            x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
            package_instance.ip_address = (
                x_forwarded_for.split(',')[0] if x_forwarded_for else request.META.get('REMOTE_ADDR')
            )

            package_instance.save()
            messages.success(request, f'Category/Type {action} successfully!')
            return redirect('masters:productcategory')

        # Form invalid
        context = self.get_context_data()
        context['form'] = form
        if packagetype_id:
            context['editing_packagetype'] = get_object_or_404(productcategory, id=packagetype_id)
        return self.render_to_response(context)



# ==================== DELETE VIEW ====================

# @login_required
def delete_package_type(request, pk):
    if request.method == 'POST':
        cat_type = get_object_or_404(productcategory, pk=pk)
        cat_type.delete()
        messages.success(request, 'Category/Type deleted successfully!')
        return redirect('masters:productcategory')

    return redirect('masters:productcategory')


# ==================== EXPORT VIEW ====================

# @login_required
def export_package_types(request, export_type):
    package = productcategory.objects.all().order_by('category_type')

    if export_type == 'excel':
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="Product_Category.csv"'

        writer = csv.writer(response)
        writer.writerow(['S.No', 'Category/Type', 'Description', 'Status', 'Created At'])

        for idx, pack in enumerate(package, 1):
            writer.writerow([
                idx,
                pack.get_category_type_display(),
                pack.description or '',
                'Active' if pack.is_active else 'Inactive',
                pack.created_at.strftime('%Y-%m-%d %H:%M:%S')
            ])

        return response

    elif export_type == 'pdf':
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="Product_Category.pdf"'

        p = canvas.Canvas(response, pagesize=letter)
        p.setTitle("Product Category")

        p.setFont("Helvetica-Bold", 16)
        p.drawString(100, 720, "Product Category List")

        data = [['S.No', 'Category/Type', 'Description', 'Status']]

        for idx, pack in enumerate(package, 1):
            description = (pack.description or '')
            if len(description) > 50:
                description = description[:50] + "..."

            data.append([
                str(idx),
                pack.get_category_type_display(),
                description or 'N/A',
                'Active' if pack.is_active else 'Inactive'
            ])

        table = Table(data)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))

        table.wrapOn(p, 400, 600)
        table.drawOn(p, 100, 600)

        p.showPage()
        p.save()
        return response

    return redirect('masters:productcategory')



    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    





class tankmasterview(TemplateView):
    template_name = "masters/tankmaster.html"

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # ✅ FIXED HERE
        all_tanks = TankMaster.objects.select_related('tank_volume').order_by('-id')

        paginator = Paginator(all_tanks, 10)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        tank_id = self.request.GET.get('edit')
        form = None
        editing_tank = None

        if tank_id:
            try:
                editing_tank = TankMaster.objects.get(id=tank_id)
                form = TankMasterForm(instance=editing_tank)
                context['editing_tank'] = editing_tank
            except TankMaster.DoesNotExist:
                messages.error(self.request, 'Tank not found!')

        if not form:
            form = TankMasterForm()

        context.update({
            'form': form,
            'tanks': page_obj,
            'queryset': page_obj,
            'total_tanks': all_tanks.count(),
        })

        return context

    def post(self, request, *args, **kwargs):
        tank_id = request.POST.get('tank_id')

        if tank_id:
            tank_instance = get_object_or_404(TankMaster, id=tank_id)
            form = TankMasterForm(request.POST, instance=tank_instance)
        else:
            form = TankMasterForm(request.POST)

        if form.is_valid():
            tank_instance = form.save(commit=False)

            if 'is_active' not in request.POST:
                tank_instance.is_active = False

            try:
                if tank_id:
                    tank_instance.updated_by = request.user
                    action = "updated"
                else:
                    tank_instance.created_by = request.user
                    tank_instance.updated_by = request.user
                    action = "created"
            except Exception:
                action = "saved"

templates/masters/crm/vehicle_type.html
{% extends "masters/base.html" %}
{% load static %}

{% block content %}

<div class="row">
    <h3 class="mt-1 mb-4">Vehicle Type Allocation</h3>

    <!-- ================= FORM ================= -->
    <div class="col-xl-4">
        <div class="card custom-card">
            <div class="card-header">
                <h5>{{ editing_vehicle_type.pk|yesno:"Edit,Add" }} Vehicle Type</h5>
            </div>

            <div class="card-body">
                <form method="post" id="VehicleTypeForm" novalidate>
                    {% csrf_token %}

                    {% if editing_vehicle_type %}
                        <input type="hidden" name="vehicle_type_id" value="{{ editing_vehicle_type.pk }}">
                    {% endif %}

                    <!-- Vehicle Type -->
                    <div class="mb-3">
                        <label class="form-label">Vehicle Type</label>
                        {{ form.vehicle_type }}
                        {% if form.vehicle_type.errors %}
                            <div class="invalid-feedback d-block">
                                {{ form.vehicle_type.errors.0 }}
                            </div>
                        {% endif %}
                    </div>

                    <!-- Active Status -->
                    <div class="mb-3">
                        <div class="form-check form-switch">
                            {{ form.is_active }}
                            <label class="form-check-label">Active</label>
                        </div>
                    </div>

                    <!-- Submit -->
                    <div class="d-flex gap-2">
                        <button type="submit" class="btn btn-warning btn-wave">
                            {{ editing_vehicle_type.pk|yesno:"Update,Save" }}
                        </button>
                        <a href="{% url 'masters:vehicle_type_master' %}" class="btn btn-danger-light btn-wave">
                            Cancel
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- ================= LIST ================= -->
    <div class="col-xl-8">
        <div class="card custom-card">
            <div class="card-header d-flex justify-content-between">
                <h5 class="mb-0">Vehicle Type List</h5>
            </div>

            <div class="card-body">
                <!-- Export + Search -->
              <div class="d-flex justify-content-between">
                    <!-- Export Buttons -->
                    <div class="">
                        <a href="{% url 'masters:export_vehicle_type_master' 'excel' %}" class="btn btn-success">
                            <i class="ri-file-excel-2-line"></i> Export Excel
                        </a>
                        <a href="{% url 'masters:export_vehicle_type_master' 'pdf' %}" class="btn btn-danger">
                            <i class="ri-file-pdf-line"></i> Export PDF
                        </a>
                    </div>
                    <div class="col-md-3">
                        <input type="search" class="form-control search-table" data-target="#searchTable" placeholder="Search...">
                    </div> 
                </div><br>

                <!-- Table -->
                <div class="table-responsive">
                    <table class="table table-bordered text-nowrap w-100" id="searchTable">
                        <thead>
                            <tr>
                                <th>S.No</th>
                                <th>Action</th>
                                <th>Vehicle Type</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for vt in vehicle_types %}
                            <tr>
                                <td>{{ forloop.counter0|add:vehicle_types.start_index }}</td>
                                <td>
                                    <a href="?edit={{ vt.id }}" class="text-info">
                                        <i class="ri-edit-line"></i>
                                    </a>

                                    {% if vt.is_used %}
                                        <span class="text-warning ms-2" title="In use">
                                            <i class="ri-lock-line"></i>
                                        </span>
                                    {% else %}
                                        <a href="javascript:void(0);"
                                           data-url="{% url 'masters:delete_vehicle_type' vt.id %}"
                                           class="text-danger delete-btn ms-2">
                                            <i class="ri-delete-bin-5-line"></i>
                                        </a>
                                    {% endif %}
                                </td>
                                <td>{{ vt.vehicle_type }}</td>
                                <td>
                                    {% if vt.is_active %}
                                        <span class="badge bg-success">Active</span>
                                    {% else %}
                                        <span class="badge bg-danger">Inactive</span>
                                    {% endif %}
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="4" class="text-center py-4">No vehicle types found</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

            <!-- Pagination -->
            <div class="card-footer">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        Showing {{ vehicle_types.start_index }} to {{ vehicle_types.end_index }}
                        of {{ vehicle_types.paginator.count }}
                    </div>

<ul class="pagination mb-0">

    {% if vehicle_types.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ vehicle_types.previous_page_number }}">
                <i class="ri-arrow-left-s-line align-middle"></i>
            </a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <span class="page-link">
                <i class="ri-arrow-left-s-line align-middle"></i>
            </span>
        </li>
    {% endif %}

    {% for i in vehicle_types.paginator.page_range %}
        {% if vehicle_types.number == i %}
            <li class="page-item active">
                <span class="page-link">{{ i }}</span>
            </li>
        {% elif i >= vehicle_types.number|add:'-2' and i <= vehicle_types.number|add:'2' %}
            <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
        {% endif %}
    {% endfor %}

    {% if vehicle_types.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ vehicle_types.next_page_number }}">
                <i class="ri-arrow-right-s-line align-middle"></i>
            </a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <span class="page-link">
                <i class="ri-arrow-right-s-line align-middle"></i>
            </span>
        </li>
    {% endif %}

</ul>

                </div>
            </div>
        </div>
    </div>
</div>

<!-- ================= SCRIPTS ================= -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
document.addEventListener("DOMContentLoaded", function () {

    // DELETE CONFIRMATION
    document.querySelectorAll(".delete-btn").forEach(btn => {
        btn.addEventListener("click", function () {
            const url = this.dataset.url;

            Swal.fire({
                title: 'Are you sure?',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then(result => {
                if (result.isConfirmed) {
                    const form = document.createElement('form');
                    form.method = 'POST';
                    form.action = url;

                    const csrf = document.querySelector('[name=csrfmiddlewaretoken]').cloneNode();
                    form.appendChild(csrf);

                    document.body.appendChild(form);
                    form.submit();
                }
            });
        });
    });

    // SEARCH
    document.querySelector(".search-table").addEventListener("input", function () {
        const value = this.value.toLowerCase();
        document.querySelectorAll("#searchTable tbody tr").forEach(row => {
            row.style.display = row.textContent.toLowerCase().includes(value) ? "" : "none";
        });
    });

    // SUCCESS MESSAGE
    {% for message in messages %}
        {% if message.tags == 'success' %}
            Swal.fire({
                icon: 'success',
                title: 'Success',
                text: '{{ message }}'
            });
        {% endif %}
    {% endfor %}
});
</script>

{% endblock %}